name: Solana Daily Airdrop

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs daily at 00:00 UTC
  workflow_dispatch:      # Allow manual triggering

env:
  RECIPIENT_ADDRESS: "FzzJuBTvpLsi517P1ELMZ7HwtFWxB4JFoRw6myraFgdB"  # Replace with your actual devnet address

jobs:
  solana-airdrop:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    # Cache Solana CLI installation
    - name: Cache Solana CLI
      id: cache-solana
      uses: actions/cache@v3
      with:
        path: ~/.local/share/solana
        key: solana-${{ runner.os }}
        
    # Correct Solana CLI installation with PATH handling
    - name: Install Solana CLI
      if: steps.cache-solana.outputs.cache-hit != 'true'
      run: |
        # Install Solana CLI
        sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
        
        # Add to PATH for current session
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
        
        # Verify installation
        solana --version
        echo "Solana CLI installed successfully"

    # Rest of your workflow...
    - name: Setup Solana config
      run: |
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
        solana config set --url devnet
        solana airdrop 2 $RECIPIENT_ADDRESS --url https://api.devnet.solana.com
        solana balance $RECIPIENT_ADDRESS
        echo "Last transaction details:"
        solana transaction-history $RECIPIENT_ADDRESS --limit 1
        
    - name: ending note
      run: |
        echo "Workflow ends"
