name: Solana Daily Setup and Test

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC
  workflow_dispatch:      # Allow manual triggering

jobs:
  solana-setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 1: Install Solana CLI
    - name: Install Solana CLI
      run: |
        curl --proto '=https' --tlsv1.2 -sSfL https://solana-install.solana.workers.dev | bash -s -- -v
        
    # Step 2: Install system dependencies
    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
            build-essential \
            pkg-config \
            libudev-dev llvm libclang-dev \
            protobuf-compiler libssl-dev

    # Step 3: Install Rust
    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        echo "$HOME/.cargo/env" >> $GITHUB_ENV
        source "$HOME/.cargo/env"
        rustc --version

    # Step 4: Install Anchor
    - name: Install Anchor
      run: |
        sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        solana --version

    # Step 5: Configure Solana
    - name: Configure Solana
      run: |
        solana config set --url devnet
        solana-keygen new --no-passphrase --force
        solana airdrop 2

    # Step 6: Test transaction
    - name: Test transaction
      run: |
        # Replace with your actual recipient address
        RECIPIENT="FzzJuBTvpLsi517P1ELMZ7HwtFWxB4JFoRw6myraFgdB"
        solana transfer --from ~/.config/solana/id.json $RECIPIENT 1.5 \
          --allow-unfunded-recipient \
          --url https://api.devnet.solana.com \
          --fee-payer ~/.config/solana/id.json

    # Step 7: Verify setup
    - name: Verify versions
      run: |
        echo "=== Versions ==="
        rustc --version
        cargo --version
        solana --version
        anchor --version
