name: Solana Daily Airdrop

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC
  workflow_dispatch:      # Allow manual triggering

env:
  RECIPIENT_ADDRESS: "FzzJuBTvpLsi517P1ELMZ7HwtFWxB4JFoRw6myraFgdB"  # Replace with your actual devnet address

jobs:
  solana-airdrop:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Correct Solana CLI installation with PATH handling
    - name: Install Solana CLI
      run: |
        # Install Solana CLI
        sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
        
        # Add to PATH for current session
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
        
        # Verify installation
        solana --version
        echo "Solana CLI installed successfully"

    # Rest of your workflow...
    - name: Setup Solana config
      run: |
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
        solana config set --url devnet
        solana-keygen new --no-passphrase --force
        solana --version

    - name: Execute daily airdrop and transfer
      run: |
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
        # Rest of your airdrop and transfer commands...
